### ISSUE TITLE
How to run your code?

### ISSUE THREAD

**Issue by JafferWilson** [huajianjiu/PPextraction#1]
Kindly update the readme with the syntax to run the code and the datasets that are required. 
Thank you.

**Comment by yuanzhiKe** [comment]
Hello, @JafferWilson . For the PPDB.py, you can firstly get ppdb2 at http://paraphrase.org/#/download. Then the scripts need a word list of the vocab. Each line a word. Then run PPDB.py using 
`python PPDB.py [vocab file] [PPDB file]`.
For the Wordnet.py, it request nltk and its wordnet packet. If you have got it, you can run it by `python Wordnet.py [vocab file]`.
For the other files, they are about an uncompleted project. Please ignore them, thank you.

**Comment by JafferWilson** [comment]
@huajianjiu  Where is this vocab file? I have downloaded the PPDB all files. Is it getting created automatically?

**Comment by yuanzhiKe** [comment]
@JafferWilson Nope. This codes are used to get the paraphrases table for a given vocab. The vocab file is the one you want to process.

**Comment by JafferWilson** [comment]
Thank you for your answers....:)
